name: Flutter CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" [

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. جلب الكود من المستودع
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. إعداد لغة Java (خطوة ضرورية جداً لبناء تطبيقات الأندرويد لاحقاً)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. إعداد بيئة Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 4. تحميل مكاتب وحزم المشروع (تم توجيهها للمجلد الصحيح)
      - name: Install dependencies
        working-directory: ./CashPay-Project-main
        run: flutter pub get

      # 5. فحص الكود والتأكد من عدم وجود أخطاء برمجية (اختياري ولكنه مفيد)
      - name: Analyze project
        working-directory: ./CashPay-Project-main
        run: flutter analyze

      # 6. تشغيل الاختبارات للتأكد من سلامة التطبيق (اختياري)
      - name: Run tests
        working-directory: ./CashPay-Project-main
        run: flutter test --no-pub

      # 7. بناء نسخة أندرويد APK للتجربة
      - name: Build APK
        working-directory: ./CashPay-Project-main
        run: flutter build apk --release
