name: Flutter Build APK

on: [push, pull_request]

jobs:
  build:
    name: Build Flutter APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java Development Kit (JDK)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.22.0'

      - name: Get Flutter Dependencies
        working-directory: CashPay-Project-main
        run: flutter pub get

      - name: Build APK
        working-directory: CashPay-Project-main
        run: flutter build apk --debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CashPay-Debug-APK
          path: CashPay-Project-main/build/app/outputs/flutter-apk/app-debug.apk
          
